--1
SELECT EMP_NAME 이름 , EMAIL 이메일 , LENGTH(EMAIL) 이메일길이 FROM EMPLOYEE;

--2

--3
SELECT * FROM EMPLOYEE;
SELECT EMP_NAME  직원명, CONCAT('19',SUBSTR(EMP_NO,1,2)) 년생, NVL(BONUS,0) 보너스 FROM EMPLOYEE
WHERE SUBSTR(EMP_NO,1,2) BETWEEN 60 AND 69;

--4
SELECT CONCAT(COUNT(PHONE),'명') 인원 FROM EMPLOYEE
WHERE SUBSTR(PHONE,1,3)!='010';

--5
SELECT EMP_NAME 직원명, CONCAT(CONCAT(EXTRACT(YEAR FROM HIRE_DATE),'년 '), CONCAT(EXTRACT(MONTH FROM HIRE_DATE),'월')) 입사년월 FROM EMPLOYEE;

--6
SELECT EMP_NAME 직원명, CONCAT(SUBSTR(EMP_NO,1,7) ,TRANSLATE(SUBSTR(EMP_NO,9,6),'0123456789','**********')) 주민번호 FROM EMPLOYEE;

--7
SELECT EMP_NAME 직원명, JOB_CODE 직급코드, TO_CHAR(SALARY*12,'L999,999,999') "연봉(원)" FROM EMPLOYEE; 

--8
SELECT EMP_NO 사번, EMP_NAME 직원명, DEPT_CODE 부서코드, HIRE_DATE 입사일 FROM EMPLOYEE
WHERE DEPT_CODE IN('D5','D9') AND EXTRACT(YEAR FROM HIRE_DATE)='2004';

--9
SELECT EMP_NAME 직원명, HIRE_DATE 입사일,  ROUND(SYSDATE-HIRE_DATE) 근무일수 FROM EMPLOYEE;

--10

--11
SELECT
SUM(DECODE(EXTRACT(YEAR FROM HIRE_DATE),'1998',1)) "1998년"
, SUM(DECODE(EXTRACT(YEAR FROM HIRE_DATE),'1999',1)) "1999년" 
, SUM(DECODE(EXTRACT(YEAR FROM HIRE_DATE),'2000',1)) "2000년"
, SUM(DECODE(EXTRACT(YEAR FROM HIRE_DATE),'2001',1)) "2001년"
, SUM(DECODE(EXTRACT(YEAR FROM HIRE_DATE),'2002',1)) "2002년"
, SUM(DECODE(EXTRACT(YEAR FROM HIRE_DATE),'2003',1)) "2003년"
, SUM(DECODE(EXTRACT(YEAR FROM HIRE_DATE),'2004',1)) "2004년"
,COUNT(HIRE_DATE) 전체직원수
FROM EMPLOYEE;

--12
SELECT EMP_NAME, DEPT_CODE,
    CASE DEPT_CODE
    WHEN 'D5' THEN '총무부'
    WHEN 'D6' THEN '기획부'
    WHEN 'D9' THEN '영업부'
    END   
FROM EMPLOYEE
WHERE DEPT_CODE IN('D5','D6','D9')
ORDER BY DEPT_CODE ASC;

--13
SELECT JOB_CODE 직급코드,COUNT(JOB_CODE) 인원수,ROUND(AVG(SALARY)) 평균급여 FROM EMPLOYEE
GROUP BY JOB_CODE
HAVING JOB_CODE!='J1'
ORDER BY JOB_CODE ASC;

--14
SELECT EXTRACT(YEAR FROM HIRE_DATE),COUNT(*) FROM EMPLOYEE
WHERE JOB_CODE!='J1'
GROUP BY EXTRACT(YEAR FROM HIRE_DATE)
ORDER BY EXTRACT(YEAR FROM HIRE_DATE);

--15
SELECT DECODE(SUBSTR(EMP_NO,8,1),1,'남',3,'남',2,'여',4,'여') 성별 ,ROUND(AVG(SALARY)) 평균연봉,COUNT(*) 인원수 FROM EMPLOYEE
GROUP BY SUBSTR(EMP_NO,8,1)
ORDER BY COUNT(*) DESC;

--16
SELECT DEPT_CODE, COUNT(CASE WHEN SUBSTR(EMP_NO,8,1) IN(1,3)  THEN 1 END) 남자, COUNT(CASE WHEN SUBSTR(EMP_NO,8,1) IN(2,4)  THEN 1 END) 여자 FROM EMPLOYEE
WHERE DEPT_CODE IS NOT NULL
GROUP BY DEPT_CODE;

--17
SELECT DEPT_CODE, COUNT(*) FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING COUNT(*)>3;

--18
SELECT DEPT_CODE, JOB_CODE,COUNT(*) FROM EMPLOYEE
GROUP BY JOB_CODE,DEPT_CODE
HAVING COUNT(*)>=3;

--19
SELECT MANAGER_ID, COUNT(*) FROM EMPLOYEE
GROUP BY MANAGER_ID
HAVING COUNT(*)>=2 AND MANAGER_ID IS NOT NULL;

--20
SELECT DEPT_TITLE, LOCAL_NAME FROM DEPARTMENT
JOIN LOCATION ON LOCATION_ID=LOCAL_CODE; 

--21
SELECT LOCAL_NAME, NATIONAL_NAME FROM LOCATION
JOIN NATIONAL ON LOCATION.NATIONAL_CODE=NATIONAL.NATIONAL_CODE;

--22
SELECT LOCAL_NAME,NATIONAL_NAME FROM LOCATION
JOIN NATIONAL USING(NATIONAL_CODE);




