SELECT * FROM TB_BOOK;
SELECT * FROM TB_WRITER;
SELECT * FROM TB_PUBLISHER;
SELECT * FROM TB_BOOK_AUTHOR;

--1
SELECT COUNT(*) FROM TB_BOOK;
SELECT COUNT(*) FROM TB_WRITER;
SELECT COUNT(*) FROM TB_PUBLISHER;
SELECT COUNT(*) FROM TB_BOOK_AUTHOR;

--3
SELECT BOOK_NO,BOOK_NM FROM TB_BOOK
WHERE LENGTH(BOOK_NM)>=25;

--4
SELECT WRITER_NM, OFFICE_TELNO, HOME_TELNO, MOBILE_NO FROM TB_WRITER
WHERE MOBILE_NO LIKE '019-%' AND WRITER_NM LIKE '김%';

--5
SELECT COUNT(*) "작가(명)" FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE='옮김';

--6
SELECT COMPOSE_TYPE,COUNT(*)FROM TB_BOOK_AUTHOR
GROUP BY COMPOSE_TYPE
HAVING COUNT(*)>300 AND COMPOSE_TYPE IS NOT NULL;

--7
SELECT BOOK_NM,ISSUE_DATE,PUBLISHER_NM FROM TB_BOOK
WHERE ISSUE_DATE=(SELECT MAX(ISSUE_DATE) FROM TB_BOOK);

--8
SELECT  "작가 이름" , "권 수"FROM(
SELECT WRITER_NM "작가 이름", COUNT(WRITER_NO) "권 수", RANK()OVER(ORDER BY COUNT(WRITER_NO) DESC) AS C FROM TB_WRITER
JOIN TB_BOOK_AUTHOR  USING(WRITER_NO)
GROUP BY WRITER_NM
)
WHERE C BETWEEN 1 AND 3;

--9
UPDATE TB_WRITER A SET REGIST_DATE =  
(SELECT MIN(ISSUE_DATE) FROM TB_BOOK 
JOIN TB_BOOK_AUTHOR USING(BOOK_NO)
WHERE A.WRITER_NO=WRITER_NO
);
--확인식
SELECT BOOK_NM,WRITER_NM, REGIST_DATE,ISSUE_DATE FROM TB_WRITER 
JOIN TB_BOOK_AUTHOR USING(WRITER_NO)
JOIN TB_BOOK USING(BOOK_NO)
ORDER BY WRITER_NM;

--10
CREATE TABLE TB_BOOK_TRANSLATOR(
BOOK_NO VARCHAR2(20) CONSTRAINT FK_BOOK_TRANSLATOR_01 REFERENCES TB_BOOK,
WRITER_NO VARCHAR2(10) CONSTRAINT FK_BOOK_TRANSLATOR_02 REFERENCES TB_WRITER,
TRANS_LANG VARCHAR2(60),
CONSTRAINT PK_BOOK_TRANSLATOR PRIMARY KEY (BOOK_NO,WRITER_NO) 
);

--11
+INSERT INTO TB_BOOK_TRANSLATOR
SELECT BOOK_NO, WRITER_NO, NULL FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE IN(' ? ','    ','    ','    ');

DELETE FROM TB_BOOK_AUTHOR;

SELECT * FROM TB_BOOK_TRANSLATOR;
SELECT * FROM TB_BOOK_AUTHOR;
ROLLBACK;

--12
SELECT BOOK_NM,WRITER_NM FROM TB_BOOK_TRANSLATOR
JOIN TB_BOOK USING(BOOK_NO)
JOIN TB_WRITER USING(WRITER_NO)
WHERE SUBSTR(BOOK_NO,1,4)=2007 ;
