--1
SELECT COUNT(*) FROM TB_BOOK;
SELECT COUNT(*) FROM TB_WRITER;
SELECT COUNT(*) FROM TB_PUBLISHER;
SELECT COUNT(*) FROM TB_BOOK_AUTHOR;

--3
SELECT BOOK_NO,BOOK_NM FROM TB_BOOK
WHERE LENGTH(BOOK_NM)>=25;

--4
SELECT WRITER_NM, OFFICE_TELNO, HOME_TELNO, MOBILE_NO FROM TB_WRITER
WHERE MOBILE_NO LIKE '019-%' AND WRITER_NM LIKE '±è%';

--5
SELECT * FROM TB_BOOK_AUTHOR;
SELECT COUNT(*) "ÀÛ°¡(¸í)" FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE='¿Å±è';

--6
SELECT * FROM TB_BOOK_AUTHOR;
SELECT COMPOSE_TYPE,COUNT(*)FROM TB_BOOK_AUTHOR
GROUP BY COMPOSE_TYPE
HAVING COUNT(*)>300 AND COMPOSE_TYPE IS NOT NULL;

--7
SELECT BOOK_NM,ISSUE_DATE,PUBLISHER_NM FROM TB_BOOK
WHERE ISSUE_DATE=MAX(ISSUE_DATE);
