--1
SELECT * FROM JOB;

--2
SELECT JOB_NAME FROM JOB;

--3
SELECT * FROM DEPARTMENT;

--4
SELECT EMP_NAME, EMAIL, PHONE, HIRE_DATE FROM EMPLOYEE;

--5
SELECT HIRE_DATE,EMP_NAME,SALARY FROM EMPLOYEE;

--6
SELECT EMP_NAME, SALARY*12, (SALARY+(SALARY*BONUS))*12,
(SALARY+(SALARY*BONUS))*12-(SALARY*0.03*12) FROM EMPLOYEE; 

--7
SELECT EMP_NAME, SALARY, HIRE_DATE,PHONE FROM EMPLOYEE
WHERE SAL_LEVEL='S1';

--8
SELECT EMP_NAME, SALARY,(SALARY+(SALARY*BONUS))*12-(SALARY*0.03*12),HIRE_DATE FROM EMPLOYEE
WHERE (SALARY+(SALARY*BONUS))*12-(SALARY*0.03*12)>=50000000;

--9
SELECT * FROM EMPLOYEE
WHERE SALARY>=4000000 AND JOB_CODE='J2';

--10
SELECT EMP_NAME, DEPT_CODE, HIRE_DATE FROM EMPLOYEE
WHERE HIRE_DATE <='02/01/01';

--11
SELECT * FROM EMPLOYEE
WHERE HIRE_DATE BETWEEN '90/01/01' AND '01/01/01';

--12
SELECT EMP_NAME FROM EMPLOYEE
WHERE EMP_NAME LIKE '__연';

--13
SELECT EMP_NAME, PHONE FROM EMPLOYEE
WHERE PHONE NOT LIKE '010________';

--14
SELECT * FROM EMPLOYEE
WHERE EMAIL LIKE'____1_%' ESCAPE 1
AND HIRE_DATE BETWEEN '90/01/01' AND '00/12/01' AND SALARY>=2700000;

--15
SELECT EMP_NAME,SUBSTR(EMP_NO,1,2),SUBSTR(EMP_NO,3,2),SUBSTR(EMP_NO,5,2),SUBSTR(EMP_NO,8,7) FROM EMPLOYEE;

--16
SELECT EMP_NAME,REPLACE(EMP_NO,SUBSTR(EMP_NO,8,7),'*******') FROM EMPLOYEE;

--17
SELECT EMP_NAME,ABS(FLOOR(HIRE_DATE-SYSDATE)),ABS(FLOOR(SYSDATE-HIRE_DATE)) FROM EMPLOYEE;

--18
SELECT * FROM EMPLOYEE
WHERE MOD(EMP_ID,2)=1;

--19
SELECT * FROM EMPLOYEE
WHERE EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM HIRE_DATE)>=25;

--20
SELECT EMP_NAME,TO_CHAR(SALARY,'L999,999,999') FROM EMPLOYEE;

--21
SELECT EMP_NO FROM EMPLOYEE;
SELECT EMP_NAME, DEPT_CODE, 
CONCAT(CONCAT(CONCAT(SUBSTR(EMP_NO,1,2),'년 '),CONCAT(SUBSTR(EMP_NO,3,2),'월 ')),CONCAT(SUBSTR(EMP_NO,5,2),'일')) AS 생년월일,
SUBSTR((EXTRACT(YEAR FROM SYSDATE)-SUBSTR(EMP_NO,1,2))+1,3,2) FROM EMPLOYEE;

--22
SELECT EMP_NO,EMP_NAME,DEPT_CODE,DECODE(DEPT_CODE,'D5','총무부','D6','기획부','D9','영업부') FROM EMPLOYEE
WHERE DEPT_CODE IN('D5','D6','D9')
ORDER BY DEPT_CODE ASC;

--23
SELECT EMP_NO,EMP_NAME,SUBSTR(EMP_NO,1,6),SUBSTR(EMP_NO,8,7),SUBSTR(EMP_NO,1,6)+SUBSTR(EMP_NO,8,7)  FROM EMPLOYEE
WHERE EMP_ID='201';

--24
SELECT SUM((SALARY+SALARY*NVL(BONUS,0))*12) FROM EMPLOYEE
WHERE DEPT_CODE='D5';

--25
SELECT COUNT(*) AS 전체직원수,
COUNT(case when SUBSTR(HIRE_DATE,1,2)='01'THEN 01 END)AS "2001년", 
COUNT(case when SUBSTR(HIRE_DATE,1,2)='02'THEN 02 END)AS "2002년",
COUNT(case when SUBSTR(HIRE_DATE,1,2)='03'THEN 03 END)AS "2003년",
COUNT(case when SUBSTR(HIRE_DATE,1,2)='04'THEN 04 END)AS "2004년"
FROM EMPLOYEE;



