CREATE TABLE MEMBER(
    IDX_NUMBER NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(10) NOT NULL,
    MEMBER_PWD VARCHAR2(10) NOT NULL,
    MEMBER_NAME VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(30),
    ADDRESS VARCHAR2(100),
    PHONE VARCHAR2(10),
    ENROLL_DATE DATE
);

INSERT INTO MEMBER
VALUES (SEQ1.NEXTVAL, 'ZZZ123', 'QWE123','홍길동','hong@gmail.com','제주도 서귀포',01012341234,SYSDATE);
INSERT INTO MEMBER
VALUES (SEQ1.NEXTVAL, 'asdg11', 'zxc123','이순신','lss@gmail.com','전라도 경주',01062416224,SYSDATE);
INSERT INTO MEMBER
VALUES (SEQ1.NEXTVAL,'aaa111', 'asd123','임꺽정','gguk@gmail.com','경기도 연천',0107239734,SYSDATE);
COMMIT;

SELECT * FROM MEMBER;

CREATE TABLE BOARD(
    IDX_NUMBER NUMBER PRIMARY KEY,
    DIV VARCHAR2(10) CHECK(DIV IN ('공지','일반','비밀')),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENTS VARCHAR2(3000) NOT NULL,
    WRITER_NUMBER REFERENCES MEMBER(IDX_NUMBER),
    WRITE_DATE DATE
);

CREATE SEQUENCE SEQ1
START WITH 100
INCREMENT BY 1;

CREATE SEQUENCE SEQ2
START WITH 1
INCREMENT BY 1;
